### ISSUE TITLE
Possible division by zero

### ISSUE THREAD

**Issue by Bbulatov** [samber/slog-multi#14]
Hello!
During the static analysis was found possible mistake:
1) Variable int64(len(h.handlers)), whose possible value set allows a zero value at pool.go:45, is used as a denominator at pool.go:45.
```
func (h *PoolHandler) Handle(ctx context.Context, r slog.Record) error {
	// round robin
	rand := h.randSource.Int63() % int64(len(h.handlers))
	handlers := append(h.handlers[rand:], h.handlers[:rand]...)
```
Please clarify whether this requires correction?

**Comment by samber** [comment]
Fixed in #15 -> v1.2.4

**Comment by samber** [comment]
@Bbulatov my SAST did not detect it. What tool do you use ?

**Comment by Bbulatov** [comment]
@samber I used [Svace](https://www.ispras.ru/en/technologies/svace/)
